In [2]:
class Annie:
    def __init__(self, health, mana, ability_power):
        self.health = health
        self.mana = mana
        self.ability_power = ability_power
    def tibbers(self):
        print(f"티버 : 피해량 {self.ability_power * 0.65 + 400}")

health, mana, ability_power = map(float, input("체력, 마나, AP를 입력하세요.").split())
x = Annie(health=health, mana=mana, ability_power=ability_power)
x.tibbers()

체력, 마나, AP를 입력하세요. 1803.68 1184.0 645


티버 : 피해량 819.25


In [3]:
class Person3:
    
    def __init__(self, name, age, address, wallet):
        self.hellot = "안녕하세요"
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet
        
    def greeting(self):
        print(f"{self.hello} 제이름은 {self.name} 입니다")
    def amount(self):
        print(self.__wallet)
    

## @classmethod 사용, @staticmethod 사용 -> 당장은 이런것이 있다정도로만 알아두자.

## `넘파이(Numpy)`   
Numpy는 파이썬 내장모듈이 아님. 따라서 별도의 설치를 요구하지만, 아나콘다에선 Numpy를 패키지 없이 사용가능

In [4]:
!conda list

# packages in environment at C:\Users\Playdata\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0 

숫자 데이터를 좀 더 쉽고 편리하게 다룰수 있음.  
다차원 배열 자료구조 클래스인 ndarray 클래스를 지원, 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용

배열(Array)란 순서가 있는 같은 종류의 데이터가 저장되는 자료형.  

넘파이 배열이 리스트보다 구조적으로 속도가 빠르고 메모리를 더 적게 사용함.

수 많은 숫자 데이터를 하나의 리스트 시퀀스로 다루게 되면 넘파이 배열에 비해 상대적으로 속도가 느리고 메모리를 많이 차지하는 단점이 있음.  
넘파이 패키지 배열(Array)을 이용하면 리스트에 비해 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음  
다만 넘파이 배열은 많은 데이터를 다룰 수 있다는 점에서 리스트와 비슷하지만 차이점이 있음.  
1. 모든 요소(items)가 같은 자료형(type)이어야 함.(리스트는 다양한 자료형을 섞어서 요소로 가질 수 있음)
2. 요소의 개수를 바꿀 수 없음.(리스트는 요소의 추가 및 삭제가 자유로움)

넘파이 배열연산은 C로 구현된 내부반복문을 사용함. 파이썬 반복문에 비해 속도가 빠르며 벡터화연산(vectorized operation)을 이용  
간단한 코드로도 복잡한 선형대수연산을 수행 가능.  
배열 인덱싱(array indexting)을 사용한 질의(Query) 기능을 이용하여 간단한 코드로도 복잡한 수식을 계산할 수 있음

### 넘파이 패키지 임포트하기  
배열을 사용하기 위해 NumPy  패키지를 임포트해야함  
`np`라는 이름으로 임포트하는 것이 관례  
하는 방법은 다음과 같음  
  
  import numpy as np

## 1차원 배열 만들기  
  
  넘파이 배열 객체인 ndarray 는 N-dimensional Array의 약자. 1차원배열,2차원배열, 3차우너 배열등 다차원 배열 자료 구조를 지원  
  넘파이(np)의 array 메서드 인수로 시퀀스 자료형을 넣으면 ndarray 클래스 객체, 즉 넘파이 배열로 변환해줌.  
  시퀀스 자료형은 튜플보단 주로 리스트를 많이 활용함.  
  만들어진 ndarray 객체의 표현식(representation)을 보면 바깥쪽에 array()란 것이 붙어 있을 뿐, 리스트와 동일한 구조처럼 보임.  
  그러나 배열객체와 리스트객체는 많은 차이가 있음.  
    
    ar = np.array([_ for _ in range(10)]  
    ar  
    array([0,1,2,3,4,5,6,7,8,9])

넘파이 배열 객체의 속성 중 shape를 사용하면 그 넘파이 배열의 모양을 확인할 수 있음.  
아래 예제 코드를 통해 앞서 생성한 배열의 모양과 차원을 확인할 수  있음. 개수가 10개인 1차원 배열이 생성된 것을 확인할 수 있음  
  
  ar.shape

In [5]:
import numpy as np

In [6]:
ar = np.array([_ for _ in range(10)])

In [7]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(id(ar))

2734602173296


In [9]:
ar.shape

(10,)

In [10]:
type(ar)

numpy.ndarray

### 넘파이와 리스트의 차이  
1. 리스트  
  요소의 종류에 관계없이, 개수에 제한없이 삽입, 삭제 수정이 가능  
2. 넘파이  
  메모리에서 연속적인 배치를 이룸, 모든 요소가 같은 자료형이어야하고 개수가 명확해야함.  
  접근이 간단하고, 요소에 대한 루프(반복문)를 효과적으로 수행할 수 있음.

In [11]:
ar2 = np.array([0.1, 5 ,4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

ar2를 보면 정수와 실수가 섞여있는 경우 표현 범위가 더 큰 자료형으로 변환한 것을 알 수 있음.

In [12]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

np.array() 함수로 넘파이 배열을 만들때 자료형을 확인하려면 키워드인자로 dtype을 이용

In [13]:
ar.dtype

dtype('int32')

In [14]:
ar2.dtype

dtype('float64')

01010101 -> 8bits == 1byte  
int32 에서 32는 bit의 크기

### 넘파이의 자료형  
'?' = boolean  | b(True,False)
'b' = (signed) byte  | i8(64비트)  
'B' = unsigned byte  | u8(64비트)  
'i' = (signed) int  | i8(64비트)  
'u' = unsigned int  | u8(64비트)  
'f' = float  | f8(64비트)  
'c' = complex  | c16(128비트)  
'O' = Object | 객체에 대한 포인터  
'U' = Unicode string

In [17]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8') # int8*8bit

In [20]:
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [21]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')


In [22]:
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [23]:
ar5 = np.array(["가나다라마" for _ in range(5)], 'U5')
print(ar5)
print(ar5.dtype)

['가나다라마' '가나다라마' '가나다라마' '가나다라마' '가나다라마']
<U5


In [25]:
ar6 = np.array(["가나다라마", "바", "사아자", "차카"], 'U2')
print(ar6)
print(ar6.dtype)

['가나' '바' '사아' '차카']
<U2


In [26]:
# U8 은 최대 8글자의 유니코드 자료형을 의미 // U2 로 했을 시 2글자만 출력이됨을 확인할 수 있음

### 넘파이의 자료형  

In [27]:
x = np.array([1,2,3], dtype = 'f')
x.dtype

dtype('float32')

In [28]:
x[0] + x[1]

3.0

In [29]:
y = np.array([1,2,3], dtype='U')
y.dtype

dtype('<U1')

In [30]:
y[0] + y[1]

'12'

숫자형태의 자료는 수연산으로 처리됨을 확인할 수 있음  
문자열자료는 concatenate가 됨을 알 수 있음

### 무한대를 표현하기 위해 np.inf(infinity)와 정의할 수 없는 숫자 np.nan(not a number)로 사용할 수 있음
  
  1을 0 으로 나누거나 0에대한 로그값은 무한대인 np.inf가 나타남.  
  0을 0으로 나누려하면 np.nan이 나타남.

In [32]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

C:\Users\Playdata\AppData\Local\Temp\ipykernel_4540\1032392073.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
C:\Users\Playdata\AppData\Local\Temp\ipykernel_4540\1032392073.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [33]:
np.log(0)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_4540\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

np.exp(-np.inf)

## 벡터화 연산(Vectorized Operation)    
넘파이 배열 객체는 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원.

In [35]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

위는 리스트의 예시.

넘파이 배열 객체는 벡터화 연산을 사용하여 for 반복문이 없이 간단하게 단 한번의 연산식으로 표현할 수 있음.  
계산 속도 또한 리스트 객체에 반복문을 사용해서 처리하는 것보다 훨씬 빠름.

In [36]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
2 * x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
list_samp = [_ for _ in range(3)]
print(list_samp *5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


리스트에선 정수를 곱하면 객체의 크기가 곱한 수만큼 반복 증가함.  
넘파이 객체는 벡터화 연산이 이루어짐을 기억해야함

In [39]:
a = np.array([1,2,3])
b = np.array([10,20,30])
2 * a + b

array([12, 24, 36])

In [40]:
a == 2

array([False,  True, False])

In [41]:
b > 10

array([False,  True,  True])

In [42]:
(a ==2) & (b>10)

array([False,  True, False])

## 2차원 배열 만들기  
2차원 배열은 행렬(matrix)라함.  
행렬에서는 가로줄을 행(row)이라하고 세로줄을 열(column)이라함

### 2차원 배열 만들기  
리스트를 중첩하여 리스트의 리스트를 이용하여 2차원 배열처럼 생성가능.  
안쪽 리스트의 길이는 행렬의 열의 수 즉 가로크기가 되고  
바깥 리스트의 길이는 행렬의 행의 수 즉 세로크기가 됨.

In [43]:
c = np.array([[0,1,2],[3,4,5]])
print(c)

[[0 1 2]
 [3 4 5]]


In [44]:
c.shape

(2, 3)

In [45]:
d= np.array([[_ for _ in range(2, 10, 2)], [_ *2 for _ in range(1,5)]])
print(d)
d.shape

[[2 4 6 8]
 [2 4 6 8]]


(2, 4)

In [46]:
example = np.array([[_*10 for _ in range(1,5)],[_*10 for _ in range(5,9)]])
print(example)

[[10 20 30 40]
 [50 60 70 80]]


## 3차원 배열 만들기  
3차원 배열의 구조는 '깊이 X 행 X 열' 모양임  
axis0 = 깊이  
axis1 = 행  
axis2 = 열

리스트의 중첩으로 만들면됨.  
크기를 나타낼때 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트의 길이의 순서로 표시

In [49]:
# 2 X 3 X 4
e = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
              [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
print(e)
print(e.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
(2, 3, 4)


### 배열의 차원과 크기 알아내기  
ndim 과 shape 이용  
ndim 은 배열의 차원, shape 는 배열의 크기를 반환

In [50]:
print(a.ndim)
print(a.shape)

1
(3,)


In [51]:
print(c.ndim)
print(c.shape)

2
(2, 3)


In [52]:
print(e.ndim)
print(e.shape)

3
(2, 3, 4)


In [53]:
a = np.array([_ for _ in range(0,5)])
a

array([0, 1, 2, 3, 4])

In [54]:
a[2]

2

In [55]:
a[-1]

4

In [56]:
list_sample = [[1,2],[3,4]]
list_sample[0]

[1, 2]

In [57]:
list_sample[0,0]

TypeError: list indices must be integers or slices, not tuple

In [58]:
list_sample[0][0]

1

In [59]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
a[0]

array([0, 1, 2])

In [61]:
a[0,0]

0

In [62]:
a[0,1]

1

In [63]:
a[-1,-1]

5

In [64]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [65]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [68]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [69]:
a[:,1] #두번째 열 전체

array([1, 5])

### reshape 사용하기

In [70]:
np.array([_ for _ in range(8)]).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
m = np.array([_ for _ in range(15)]).reshape(3,5)

In [73]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [88]:
print(m[1,2])
print(m[-1,-1])
print(m[1, 1:3])
print(m[1:3,2])
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


## 배열 생성  
NumPy는 몇가지 단순한 배열을 생성하는 메서드를 제공  
1. zeros, ones
2. zeros_like, ones_like
3. empty
4. arange
5. linspace, logspace

### zeros

In [89]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [90]:
c = np.zeros((5,2), dtype= "i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [91]:
d = np.zeros(5, dtype='U4')

In [92]:
d

array(['', '', '', '', ''], dtype='<U4')

In [93]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

### ones

In [95]:
e = np.ones((2,3,4), dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

### ones_like, zeros_like 

In [97]:
f = np.ones_like (e, dtype="f")
f

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [98]:
g = np.empty((4,3))
g

array([[0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125]])

### 배열생성시 empty 사용하면 빠르게 만들수있음.

### arange 사용  
arange는 NumPy 버전의 range 명령이라 볼수있음.

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

### linspace & logspace  
선형구간 또는 로그구간을 지정한 구간의 수만큼 분할

In [101]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [102]:
np.logspace(0,100,5)

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [103]:
ex3 = np.arange(13)
ex3.reshape(3,4)

ValueError: cannot reshape array of size 13 into shape (3,4)

In [105]:
ex4 = np.arange(12)
ex4.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
ex4.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [107]:
ex4.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
ex4.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### 다차원배열

In [109]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [110]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [111]:
x.reshape(5,-1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

엄연히 다른 객체임을 알 수있음

## 1차원만 증가시키는 경우 newaxis 사용

In [112]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결  
행의 수 & 열의 수가 같은 두개 이상의 배열을 연결(concatenate)하여 더 큰 배열을 만드는 것  
1. hstack
2. vstack
3. dstack
4. stack
5. r_
6. c_
7. tile

### 1.hstack  
hstack 명령은 행의 수가 같은 두 개 이상의 배열을 앞으로 연결하여 열의 수가 더 많은 배열을 만듬.

In [113]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [116]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

### 2. vstack  
vstack은 열의 수가 같은 두 개 이상의 배열을 아래로 연결하여 행의 수가 더 많은 배열을 만듬

In [122]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [123]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3. dstack  
dstack 은 제 3의 축, 즉 깊이 방향으로 배열을 합침.  
가장 내부의 숫자 원소가 배열이 됨.

In [125]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [126]:
c2 = np.zeros((3,4))

In [127]:
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [128]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [129]:
np.dstack([c2,c1])

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [130]:
 c = np.stack([c1,c2])

In [131]:
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [132]:
c.shape

(2, 3, 4)

In [135]:
c_axis1 = np.stack([c1,c2], axis=1)

In [143]:
print(c_axis1)
c_axis1.shape

[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


(3, 2, 4)

c_axis0 = np.stack([c1,c2], axis=0)

In [141]:
print(c_axis0)
c_axis0.shape

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


(2, 3, 4)

In [142]:
c_axis2 = np.stack([c1,c2], axis=2)
print(c_axis2)
c_axis2.shape

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


(3, 4, 2)

### r_ 메서드  
hstack 명령과 비슷하게 배열을 좌우로 연결. 그러나 메서드임에도 소괄호를 사용하지 않고, 인덱싱과 같이 대괄호를 사용함.  
인덱서(indexer)라고 함

In [146]:
np.r_[(np.array([1,2,3]), np.array([4,5,6]))]

array([1, 2, 3, 4, 5, 6])

### c_ 메서드  
배열의 차원을 증가시킨 후 좌우로 연결.

In [147]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

### tile 메서드  
동일한 배열을 반복하여 연결

In [150]:
a = np.array([[0,1,2],[3,4,5]])
print(np.tile(a, 2))
np.tile(a,2).shape

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


(2, 6)

In [151]:
print(np.tile(a, (3,2)))
np.tile(a, (3,2)).shape

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


(6, 6)

### 연습문제

In [152]:
a1 = np.zeros((3,3))
print(a1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [154]:
a2 = np.ones((3,2))
print(a2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [157]:
a3 = np.arange(10,160,10).reshape(3,5)
print(a3)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [158]:
sum1 = np.hstack([a1,a2])
print(sum1)

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]


In [159]:
sum2 = np.vstack([sum1, a3])
print(sum2)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


In [166]:
a1 = np.zeros((3,3))
a2 = np.ones((3,2))
a3 = np.arange(10,160,10).reshape(3,5)
sum1 = np.hstack([a1,a2])
sum2 = np.vstack([sum1, a3])
tot = np.tile(sum2, (2,1))
print(tot)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


In [169]:
a1 = np.zeros((3,3))
a2 = np.ones((3,2))
a3 = np.arange(10,160,10).reshape(3,5)
sum3 = np.tile(np.vstack([np.hstack([a1,a2]),a3]), (2,1))
print(sum3)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]
