In [1]:
class ClassName:
    def __init__(self, param1, param2):
        self.attr1 = param1
        self.attr2 = param2

던더 __ 를 사용하면 비공개 속성이 됨.

비공개의 의미는 private, 즉 접근을 제한하는, 변경을 못하도록 막음

## Class + NumPy 연습문제

In [116]:
import numpy as np
class Calculator:
    
    def __init__(self):
        self.value = 0
        
    def add(self, *args): #가변인자는 None을 가질 수 없음. 가변인자 기본 자료형은 tuple
        if len(args) == 0 :
            print(f"숫자를 입력해주세요")
            return
        self.value = self.value + np.sum(args) # numpy 구조로 더하기
        
    def minus(self, *args):
        if len(args) == 0:
            print(f"숫자를 입력해주세요")
            return
        self.value = self.value - np.sum(args) #numpy 구조로 빼기
        
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")

In [117]:
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()

현재 값은 80입니다.


In [118]:
c.add()

숫자를 입력해주세요


In [119]:
c.minus([10,20])

In [120]:
c.show_value()

현재 값은 50입니다.


In [121]:
c.add(range(1,6))

In [122]:
c.show_value()

현재 값은 65입니다.


In [154]:
import numpy as np
class Calculator:
    
    def __init__(self):
        self.value = 0
        
    def add(self, *args): #가변인자는 None을 가질 수 없음. 가변인자 기본 자료형은 tuple
        print(type(args))
        if len(args) == 0:
            print(f"숫자를 입력해주세요")
            return
        for i in args: # str 입력을 반환
            if type(i) == str:
                print(f"숫자를 입력해주세요")
                return
        self.value = self.value + np.sum(args) # numpy 구조로 더하기
        
    def minus(self, *args):
        if len(args) == 0:
            print(f"숫자를 입력해주세요")
            return
        self.value = self.value - np.sum(args) #numpy 구조로 빼기
        
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")

In [155]:
c = Calculator()
c.add(100)
c.minus(20)
c.show_value()

<class 'tuple'>
현재 값은 80입니다.


In [156]:
c.add()

<class 'tuple'>
숫자를 입력해주세요


In [157]:
c.add('k')

<class 'tuple'>
숫자를 입력해주세요


## 벡터화 연산  
반복문을 사용하지 않고 배열의 모든 원소에 대해 반복 연산을 할 수 있음.  


In [163]:
# import time
x = np.arange(1,10001)
y = np.arange(10001,20001)

# %%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

In [164]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [165]:
a >= b

array([False,  True,  True,  True])

In [166]:
c = np.array([1,2,3,4])

In [167]:
np.all(a ==b)

False

In [168]:
np.all(a==c)

True

In [169]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [171]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

### 브로드캐스팅  
넘파이 배열은 모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환시켜주는 브로드캐스팅을 지원  
넘파이가 처리하는 브로드캐스팅의 방법은 더 작은 배열이 더 큰 배열에 호환되는 모양으로 확장하는 식으로 진행

In [173]:
a = np.array([1.0,2.0,3.0])
b = 2.0
a*b

array([2., 4., 6.])

## 브로드캐스팅  
모든 경우에 가능한가?  
-> 모든경우가 가능한 것은 아님

확장 가능한 경우의 규칙은 다음과 같음.  
  
  넘파이 배열의 shape을 우측 정렬하고 각 차원별로 숫자를 비교함.  
  비교하는 모든 차원이 두 조건 중 하나에 충족되어야 브로드캐스팅이 가능  
  1. 해당 차원간의 숫자가 동일한 경우
  2. 해당 차원 중 하나가 1인 경우

## 차원축소연산  
행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 됨.  
예를 들어 10 X 5 크기의 2차원 배열에 대해 행-평균을 구하면 10개의 숫자를 가진 1차원 벡터가 나오게됨.  
이런 연산을 차원축소(dimension reduction)연산이라함.  
넘파이는 다음과 같은 차원 축소연산명령 혹은 메서드를 지원  
최대/최소 : min, max, argmin, argmax  
통계 : sum, mean, median, std, var  
불리언 : all, any

### 차원 축소 연산 - sum()  
sum() 메서드는 해당 배열의 합산 결과를 반환함. 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있음.

In [174]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [175]:
np.sum(x)

10

In [176]:
x.sum()

10

In [217]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [218]:
x.sum(axis=0) #axis = 0은 행 간의 연산 결과를 구한다.

array([12, 15, 18, 21])

In [219]:
x.sum(axis=1) # axis = 1은 열 간의 연산 결과를 구한다.

array([ 6, 22, 38])

### np.sum() 과 ndarray.sum() 은 동등한 메서드임.

### 차원 축소 연산 - min()  
min() 메서드는 해당 배열의 제일 작은 값의 결과를 반환. 연산 대상이 2차원이상일 때에는 axis 키워드 인수를 사용가능

In [183]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [184]:
x.min()

0

In [185]:
np.min(x)

0

In [186]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [187]:
np.min(x, axis=1)

array([[ 0,  1],
       [10, 11]])

In [188]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### iterable(반복가능한가?) 확인하기

In [189]:
hasattr(range, "__iter__") # True이면 iterable 하다는 것

True

### 차원축소 연산 - argmin()  
argmin() 메서드는 해당 배열의 제일 작은 값의 인덱스를 반환. 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용할 수 있음.

In [190]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [191]:
x.argmin()

0

In [192]:
np.argmin(x)

0

In [193]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [194]:
np.argmin(x, axis = 1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [195]:
x.argmin(axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

### 차원축소연산 - max()  
max()메서드는 해당 배열의 제일 큰 값의 결과를 반환. 마찬가지로 axis 키워드 인수 사용가능

In [196]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [197]:
x.max()

19

In [199]:
np.max(x)

19

In [200]:
x.max(axis=0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [201]:
np.max(x,axis=1)

array([[ 8,  9],
       [18, 19]])

In [202]:
x.max(axis=2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

### 차원축소연산 - argmax() 
argmax() 메서드는 해당 배열의 제일 큰 값의 인덱스를 반환. 2차원이상일 때 마찬가지로 axis 키워드 인수 이용가능

In [203]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [204]:
x.argmax()

19

In [205]:
np.argmax(x)

19

In [206]:
x.argmax(axis=0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [207]:
np.argmax(x, axis=1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [208]:
np.argmax(x, axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

### 차원축소연산 -mean(), median(), np.all(), np.any()  
1. mean() : 평균
2. median() : 중앙값
3. np.all() : 배열 요소가 모두 True일 때 True를 반환.(하나라도 False이면 False)
4. np.any() : 배열 요소가 하나라도 True 이면 True반환 (전부 False 이면 False)

### 연습문제

In [220]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [221]:
print(np.max(practice))
print(np.sum(practice,axis=0))
print(np.max(practice,axis=0))
print(np.mean(practice,axis=1))
print(np.min(practice, axis=1))

9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[5.33333333 5.11666667 5.71666667 4.11666667 4.95      ]
[1.1 2.7 0.7 0.2 2.7]


In [222]:
print(np.max(practice))
print(np.sum(practice,axis=1))
print(np.max(practice,axis=1))
print(np.mean(practice,axis=0))
print(np.min(practice, axis=0))

9.0
[32.  30.7 34.3 24.7 29.7]
[8.  9.  8.9 8.2 8.9]
[4.02 5.4  4.72 5.2  5.64 5.3 ]
[0.7 1.1 2.7 2.1 2.8 0.2]


## 정렬  
numpy.sort() 를 사용하여 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만들 수도 있음.  
2차원 이상의 경우에는 행이나 열을 각각 따로따로 정렬하는데 axis인수를 사용하여 행을 정렬할 것인지 열을 정렬할 것인지 결정.  
axis = 0이면 각각의 행을 따로따로 정렬하고, axis = 1 이면 각각의 열을 따로따로 정렬함.  
디폴트 값은 -1 즉, 가장 안쪽(나중)의 차원임.

In [223]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [225]:
np.sort(a) # axis = -1 or axis = 1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [226]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [227]:
b = a +1
b

array([[ 5,  4,  6,  8],
       [ 2, 13, 12, 10],
       [ 3, 16,  2, 15]])

In [231]:
c = np.stack([a,b])
c

array([[[ 4,  3,  5,  7],
        [ 1, 12, 11,  9],
        [ 2, 15,  1, 14]],

       [[ 5,  4,  6,  8],
        [ 2, 13, 12, 10],
        [ 3, 16,  2, 15]]])

In [232]:
np.sort(c)

array([[[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]],

       [[ 4,  5,  6,  8],
        [ 2, 10, 12, 13],
        [ 2,  3, 15, 16]]])

In [233]:
np.sort(c, axis = 0)

array([[[ 4,  3,  5,  7],
        [ 1, 12, 11,  9],
        [ 2, 15,  1, 14]],

       [[ 5,  4,  6,  8],
        [ 2, 13, 12, 10],
        [ 3, 16,  2, 15]]])

In [234]:
np.sort(c,axis=2)

array([[[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]],

       [[ 4,  5,  6,  8],
        [ 2, 10, 12, 13],
        [ 2,  3, 15, 16]]])

### 순서만 알고 싶다면 argsort() 사용

In [235]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [236]:
a[j]

array([12, 25, 38, 42])

In [237]:
np.sort(a)

array([12, 25, 38, 42])

### 고급 인덱싱 - 인덱스 배열을 사용한 인덱싱  
인덱싱을 할 때 인덱스 위치를 나타내는 배열을 활용하여 인덱싱이 가능하다.  

In [238]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [240]:
print(a[[0,1,2], [0,1,0]]) # a[0,0] ,a[1,1], a[2,0]을 인덷ㄱ스로 하는 1차원 배열을 출력.

[1 4 5]


슬라이싱 범위도 결국 인덱스 배열이라고 생각하면 된다.

In [241]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [242]:
print(a[:, [0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


### 연습문제

In [249]:
scores = np.array([[1, 2, 3, 4],
                  [46, 99, 100, 71],
                  [81, 59, 90, 100]])
scores

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [250]:
lin = np.argsort(scores[1, :])

In [251]:
lin

array([0, 3, 1, 2], dtype=int64)

In [252]:
scores[: , lin]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 기술통계  

In [253]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, 15, -1,4, -7,-24, 7, 9, -6, 23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

### 표본평균 (sample average, sample mean)  
np.mean() 로 사용

In [254]:
np.mean(x)

4.8076923076923075

### 표본 분산(sample variance)  
데이터와 표본 평균간의 거리의 제곱의 평균  
np.var()

In [255]:
np.var(x)

115.23224852071006

### 표본 표준편차 / 최댓값 최소값/ 중앙값  
np.std() / np.max() & np.min() / np.median()

In [257]:
np.std(x)

10.734628476137871

In [259]:
np.median(x)

5.0

### 사분위수 (quartile)  
가장 작은 수부터 큰 수까지 크기가 커지는 순서대로 정렬했을 때 4등분 위치에 있는 수를 의미.

In [268]:
np.percentile(x,0) # 최소값

-24.0

In [269]:
np.percentile(x,25) #1사분위

0.0

In [270]:
np.percentile(x,50) #2사분위

5.0

In [271]:
np.percentile(x,75) #3사분위

10.0

In [272]:
np.percentile(x,100) # 최댓값

23.0

## 난수발생과 카운팅  
Numpy에서 random서브패키지가 있음.  
numpy.random을 이용 <=> 표준라이브러리인 random과는 다름

### 시드 설정하기  
컴퓨터 프로그램에서 발생하는 무작위 수는 엄격한 의미의 무작위 수가 아님.  
어떤 특정한 시작 숫자를 정해주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성.  
이런 기준이 되는 시작 숫자를 시드(seed) 라고 함.  
일단 생성이 된 난수는 다음 번 난수 생성을 위한 시드값이 됨.  
따라서 시드값은 한 번만 정해주면 됨.  
시드는 보통 현재 시각을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음.

### 파이썬에서 시드를 설정하는 함수는 seed임. 인수로는 0과 같거나 큰 정수를 넣어줌  
  
  np.random.seed(0)
  
이렇게 시드를 설정한 후 넘파이 random 서브퍀키지에 있는 rand함수로 5개의 난수를 생성

In [273]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [274]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [275]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [276]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [277]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [278]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

### 데이터의 순서 바꾸기  
shuffle 함수 이용 -> shuffle 함수도 자체 변환 함수이므로 한번 사용하면 변수의 값이 변경됨.  

In [279]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [280]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

### 데이터 샘플링  
데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 혹은 샘플링(sampling)이라함.  
choice 함수를 이용.  
  
  numpy.random.choice(a, size= None, replace = True, p=None)  
  
a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성  
size : 정수, 샘플 숫자.  
replace : 불리언. True 이면 한번 선택한 데이터를 다시 선택 가능  
p : 배열, 각 데이터가 선택될 수 있는 확률.

In [292]:
np.random.choice(5, 5, replace=False) #shuffle 명령과 같음

array([3, 1, 2, 0, 4])

In [293]:
np.random.choice(5, 5, replace=False) #shuffle 명령과 같음

array([0, 1, 2, 3, 4])

In [294]:
np.random.choice(5, 5, replace=False) #shuffle 명령과 같음

array([4, 2, 3, 1, 0])

In [296]:
np.random.choice(5, 3, replace=False) #3개만 선택

array([3, 4, 2])

In [297]:
np.random.choice(5, 10) #반복해서 10개 선택

array([2, 0, 3, 2, 2, 0, 1, 0, 2, 2])

In [298]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) #선택확률을 다르게해서 10개 선택

array([3, 2, 3, 3, 3, 3, 2, 3, 3, 3])

p의 합은 1

### 난수 생성  
1. rand: 0부터 1사이의 균일 분포
2. randn : 표준 정규 분포
3. randint : 균일 분포의 정수 난수

In [299]:
np.random.rand(10)

array([0.91672295, 0.92115761, 0.08311249, 0.27771856, 0.0093567 ,
       0.84234208, 0.64717414, 0.84138612, 0.26473016, 0.39782075])

In [300]:
np.random.rand(3,5)

array([[0.55282148, 0.16494046, 0.36980809, 0.14644176, 0.56961841],
       [0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828],
       [0.89603839, 0.63892108, 0.89155444, 0.68005557, 0.44919774]])

np.random.rand(3,5) -> 3,5 array 생성

randn 함수의 기댓값은 0 이고 표준편차가 1인 표준 정규분포를 따르는 난수를 생성. 

In [301]:
np.random.randn(10)

array([-0.475776  ,  1.44073112, -1.14907568,  0.80571455,  1.75610703,
        0.97297991, -1.55111911,  0.19114348,  1.60477607, -1.42002593])

In [302]:
np.random.randn(3,5)

array([[-2.44378268, -2.05633855, -0.99225755,  1.01128532,  1.40044008],
       [-0.65499168, -0.25579069, -0.71438561, -0.50083877,  0.05564534],
       [-0.48896178, -0.37992245,  0.25973465, -1.68134864, -0.91679481]])

randint함수는 다음과 같은 인수를 가짐  
numpy.random.randint(low, high=None, size = None)  
만약 high를 입력하지 않으면, 0과 low사이의숫자를, high를 입력하면 low 와 high사이의 숫자를 출력  
size 는 난수의 개수

In [303]:
np.random.randint(1,2,100)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [304]:
import random

In [308]:
[random.randint(1,2) for _ in range(100)]

[2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 1]

In [317]:
np.random.seed(0)
x = [random.randint(0,1) for _ in range(100)]
# count = x.count(1)
percent = x.count(1) / len(x)
print(percent)

0.45


In [323]:
np.random.seed(0)
a = [np.random.randint(1,7,100)]
print(a)
np.mean(a)

[array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2, 6, 1,
       2, 5, 4, 1, 4, 6, 1, 3, 4, 1, 2, 4, 6, 4, 4, 1, 2, 2, 2, 1, 3, 5,
       4, 4, 3, 5, 3, 1, 1, 5, 6, 6, 1, 5, 2, 5, 2, 3, 3, 1, 2, 2, 2, 2,
       4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5, 5, 5, 4, 5, 5, 5, 1, 5, 4,
       3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1])]


3.42

### 정수 데이터 카운팅  
난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석할 수 있읔.  
unique() 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력.  
return_counts 인수를 True로 설정하면 각 값의 데이터 개수도  출력.

In [324]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [325]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)

In [326]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [327]:
count

array([2, 2, 1], dtype=int64)

unique() 는 데이터에 존재하는 값에 대해서만 개수를 셈.  
데이터 값이 없는 경우에는 정보를 주지 않음.  
예를 들어 주사위를 10번 던졌는데 6이 한번도 나오지 않으면 이 값을 0으로 세어주지 않음.  
따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 bincount() 함수에 minlength 인수를 설정하여 쓰는 것이 더 편리함.  
bincount 함수는 0부터 minlength -1 까지의 숫자에 대해 각각 카운트를 함. 데이터가 없는 경우 카운트 값이 0

In [328]:
np.bincount([1,1,2,2,2,3], minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)