### (문제1) arange()를 활용하여 array([2, 5, 8, 11, 14, 17, 20])의 값을 갖는 ndarray 를 만드세요.

In [6]:
import numpy as np
import pandas as pd

In [7]:
np.arange(2, 21, 3)

array([ 2,  5,  8, 11, 14, 17, 20])

## (문제2) 클래스 정의부 중 __init__(self)에서 self에 대해 설명해보세요

[__init__] 은 인스턴스를 초기화하는데, 클래스의 인스턴스의 어트리뷰트로서 호출되면, 첫번째 인자로 인스턴스객체를 받음. 이때 첫번째 인자를 설정 안하면 에러가 나타나고, 그 첫 인자를 self라함..
(-> 다시 재정리 필요)

## (문제3) 정의할 수 없는 숫자(NaN)의 데이터 타입이 무엇인지 적어보세요.

float 자료형

## (문제4) 넘파이 배열에 대한 설명으로 옳은 것은?  
1. 넘파이 배열 내에 다양한 잘형이 올 수 있다.
2. 넘파이 배열의 크기는 필요에 따라 가변적으로 변경할 수 있다.
3. 넘파이 배열은 벡터화 연산이 가능하다.
4. 속도가 빠르기 때문에 메모리의 사용이 리스트에 비해 많다.
5. np.array([1,11,2,7,9.2,10.7])의 dtype은 int이다.

3

## (문제5) 다음 실행 결과와 같이 index가 '일','이','삼'이고 values가 1,2,3인 Series를 만들어보세요.

In [10]:
index = ['일','이','삼']
values = [1,2,3]
columns = [" "]
ser = pd.DataFrame(values, index= index, columns = columns)

In [12]:
ser[" "]

일    1
이    2
삼    3
Name:  , dtype: int64

## (문제6) 브로드캐스팅할 수 없는 것을 모두 고르세요.  
1. np.array([[2,3,4],[5,6,7]]) * np.arange(3)
2. np.arange(10).reshape(2,5) + np.arange(15).reshape(3,5)
3. np.zeros((3, 3, 2, 1)) - np.ones((3,2,1))
4. np.empty((2,1,7,5,1)) / np.ones((5,5))
5. np.array([[1,2,3],[4,8,12]]) * np.array([1,2,3,4,5,6])

In [14]:
np.array([[2,3,4],[5,6,7]]) * np.arange(3)

array([[ 0,  3,  8],
       [ 0,  6, 14]])

In [15]:
np.arange(10).reshape(2,5) + np.arange(15).reshape(3,5)

ValueError: operands could not be broadcast together with shapes (2,5) (3,5) 

In [16]:
 np.zeros((3, 3, 2, 1)) - np.ones((3,2,1))

array([[[[-1.],
         [-1.]],

        [[-1.],
         [-1.]],

        [[-1.],
         [-1.]]],


       [[[-1.],
         [-1.]],

        [[-1.],
         [-1.]],

        [[-1.],
         [-1.]]],


       [[[-1.],
         [-1.]],

        [[-1.],
         [-1.]],

        [[-1.],
         [-1.]]]])

In [17]:
np.empty((2,1,7,5,1)) / np.ones((5,5))

array([[[[[ 9.17677492e+170,  9.17677492e+170,  9.17677492e+170,
            9.17677492e+170,  9.17677492e+170],
          [ 9.10250472e+223,  9.10250472e+223,  9.10250472e+223,
            9.10250472e+223,  9.10250472e+223],
          [ 3.91409455e-313,  3.91409455e-313,  3.91409455e-313,
            3.91409455e-313,  3.91409455e-313],
          [ 9.74651484e+199,  9.74651484e+199,  9.74651484e+199,
            9.74651484e+199,  9.74651484e+199],
          [ 3.03377469e-298,  3.03377469e-298,  3.03377469e-298,
            3.03377469e-298,  3.03377469e-298]],

         [[ 5.77223159e+279,  5.77223159e+279,  5.77223159e+279,
            5.77223159e+279,  5.77223159e+279],
          [ 1.47365945e-312,  1.47365945e-312,  1.47365945e-312,
            1.47365945e-312,  1.47365945e-312],
          [ 2.49712390e-307,  2.49712390e-307,  2.49712390e-307,
            2.49712390e-307,  2.49712390e-307],
          [-8.58995445e+009, -8.58995445e+009, -8.58995445e+009,
           -8.58995445e+009, 

In [18]:
np.array([[1,2,3],[4,8,12]]) * np.array([1,2,3,4,5,6])

ValueError: operands could not be broadcast together with shapes (2,3) (6,) 

2, 5  
shape이 달라서 broadcasting이 안되는 것을 알 수 있었음.

## (문제7) 다음 중 차원 축소 시키는 연산이 아닌 것을 고르세요.
1. np.sum()
2. np.max()
3. np.min()
4. np.all()
5. np.sqrt()

5 -> 유니버셜 Function

## (문제8) 다음 설명 중 옳은 것을 모두 고르세요
1. DataFrame의 각 column은 각기 다른 dtype을 가질 수 있다.
2. Series의 각 값들은 서로 다른 type을 가질 수 있다.
3. DataFrame을 생성할 때 index 키워드 인수는 row index, columns 는 column index이다.
4. DataFrame을 row 단위로 인덱싱 할 때 loc(), iloc()을 활용하는 것이 좋다.
5. DataFrame에 fillna()메서드를 활용해서 NaN 값을 원하는 값을 변경할 수 있다.

1, 3, 4, 5

## (문제9) DataFrame에 대해 카테고리별 개수를 반환해주는 메서드를 고르세요.
1. DataFrame.sort_values()
2. DataFrame.count()
3. DataFrame.value_counts()
4. DataFrame.loc()
5. DataFrame.to_csv()

3  
2 -> column 별 개수를 반환

## (문제10) 코드의 결과가 DataFrame이 아닌 것을 고르세요
1. DataFrame.loc[0:1] --> row가 충분히 많을 때
2. pandas.read_csv("file.csv")
3. DataFrame[["column label1", "column label2"]] --> 둘 다 모두 존재할때
4. DataFrame.astype() -> 오류 없이 잘 동작할 때
5. DataFrame.value_counts()

5?